export type JobStatus = 
  | 'pending' 
  | 'analyzing' 
  | 'generating_storyboard' // New: Generating static images
  | 'waiting_for_approval'  // New: Stopped here, waiting for user
  | 'generating_video'      // Was 'composing_music' / parallel
  | 'stitching' 
  | 'completed' 
  | 'failed';

export interface Scene {
  id: string; // uuid
  prompt: string;
  imageUrl?: string; // Generated by Grok
  videoUrl?: string; // Generated by Fal later
  status: 'pending' | 'generating_image' | 'image_ready' | 'generating_video' | 'video_ready' | 'failed';
}

export interface JobResult {
  videoUrl?: string;
  imagesUrl?: string;
}

export interface Job {
  id: string;
  status: JobStatus;
  createdAt: number;
  input: {
    imageUrl?: string;
    style: string;
    hookText?: string;
  };
  storyboard?: Scene[]; // The 6 scenes
  musicPrompt?: string;
  audioUrl?: string;
  result?: JobResult;
  error?: string;
  logs: string[];
}

export interface CreateJobRequest {
  imageUrl: string;
  style: string;
  hookText?: string;
}

export interface CreateJobResponse {
  jobId: string;
}

export interface JobStatusResponse {
  job: Job;
}
